// <auto-generated />
using System;
using Affiant.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Affiant.EntityFramework.Migrations
{
    [DbContext(typeof(AffiantDbContext))]
    [Migration("20260430160642_InitialAffiantSchema")]
    partial class InitialAffiantSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Affiant.EntityFramework.Models.ChatMessageEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Arguments");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FunctionName")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<string>("ModelId")
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId", "Ordinal");

                    b.ToTable("ChatMessages", "affiant");
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ChatSessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("ChatSessions", "affiant");
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ConversationContextEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("EntitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Entities");

                    b.Property<string>("FieldValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("FieldValues");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProvenanceChainsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProvenanceChains");

                    b.HasKey("SessionId");

                    b.ToTable("ConversationContexts", "affiant");
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ChatMessageEntity", b =>
                {
                    b.HasOne("Affiant.EntityFramework.Models.ChatSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ConversationContextEntity", b =>
                {
                    b.HasOne("Affiant.EntityFramework.Models.ChatSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
