// <auto-generated />
using System;
using Affiant.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Affiant.EntityFramework.Migrations
{
    [DbContext(typeof(AffiantDbContext))]
    partial class AffiantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Affiant.EntityFramework.Models.ChatMessageEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Arguments");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FunctionName")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<string>("ModelId")
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId", "Ordinal");

                    b.ToTable("ChatMessages", "affiant");
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ChatSessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("ChatSessions", "affiant");
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ConversationContextEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("EntitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Entities");

                    b.Property<string>("FieldValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("FieldValues");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProvenanceChainsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProvenanceChains");

                    b.HasKey("SessionId");

                    b.ToTable("ConversationContexts", "affiant");
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.DocketEntryEntity", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffidavitJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("Affidavit");

                    b.Property<string>("AmendedAffidavitJson")
                        .HasColumnType("text");

                    b.Property<string>("AmendedProvenanceChainsJson")
                        .HasColumnType("text");

                    b.Property<string>("AmendmentsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Amendments");

                    b.Property<string>("AttestationJson")
                        .HasColumnType("text");

                    b.Property<string>("BlockedJson")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .HasColumnType("text");

                    b.Property<string>("CompositeRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedAtTicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DecidedAtTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("DecisionJson")
                        .HasColumnType("text");

                    b.Property<string>("Execution")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionDetail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpiresAtTicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreservedAmendmentsJson")
                        .HasColumnType("text");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("0.1.0");

                    b.Property<string>("ProvenanceChainsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("ProvenanceChains");

                    b.Property<Guid?>("ResubmittedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerUserId")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("Supersedes")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntryId");

                    b.HasIndex("ResubmittedTo");

                    b.HasIndex("Supersedes");

                    b.HasIndex("SessionId", "Status");

                    b.HasIndex("Status", "DecidedAtTicks");

                    b.HasIndex("Status", "ExpiresAtTicks");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "Status", "CreatedAtTicks");

                    b.ToTable("Docket", "affiant");
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ChatMessageEntity", b =>
                {
                    b.HasOne("Affiant.EntityFramework.Models.ChatSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Affiant.EntityFramework.Models.ConversationContextEntity", b =>
                {
                    b.HasOne("Affiant.EntityFramework.Models.ChatSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
